formatters:
  enable:
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable:
    - errcheck
  enable:
    - nakedret
    - whitespace
  exclusions:
    generated: strict
    rules:
      - path: (.+)\.go$
        text: 'shadow: declaration of "err" shadows declaration at line (\d+)'
    warn-unused: true
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
run:
  issues-exit-code: 1
  tests: true
version: "2"
