version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - nakedret
    - whitespace
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    rules:
      - path: (.+)\.go$
        text: 'shadow: declaration of "err" shadows declaration at line (\d+)'
    warn-unused: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
